### ISSUE TITLE
Cheat sheet update/refactor proposal: Authentication_Cheat_Sheet

### ISSUE THREAD

**Issue by mackowski** [OWASP/CheatSheetSeries#107] opened 2019-05-15 06:49 UTC
Update [Password Complexity](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Authentication_Cheat_Sheet.md#password-complexity) section. 
I want to include some tips from [this Troy's Hunt article](https://www.troyhunt.com/passwords-evolved-authentication-guidance-for-the-modern-era/). In particulate I think that we should eliminate complex characters rules in exchange for for long passwords and support for password managers (e.i. allow paste password)

**Comment by righettod** [comment] 2019-05-15 06:50
Good idea 😃

**Comment by fabienleite** [comment] 2019-05-15 18:12
Hello, I think a good idea would be to link or paraphrase the [OWASP ASVS section for password security requirements](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#v21-password-security-requirements).
These checks tells the whole story about password complexity.

**Comment by mackowski** [comment] 2019-05-18 19:17
Great idea about ASVS @fabienleite do you want to help with it?

**Comment by fabienleite** [comment] 2019-05-20 16:42
Hey,

Yes, I'm always ready to help if that's not urgent.

Just two questions before I start working on this:

- Do you prefer a link or paraphrase ? (I think a link would be better since CS are supposed to be as short as possible)
- There is sections about giving user tips about the current complexity of his password while he is choosing it **and** checking common passwords. There is a great lib that does both which is [zxcvbn](https://github.com/dropbox/zxcvbn). It's very good but the problem is that it's not maintained anymore and I do not know any alternative in JS. Do I recommend this lib with a warning ? Do you know another one that is well maintained ?

**Comment by mackowski** [comment] 2019-05-21 07:23
Link with summarise (1-2 sentences) will be better IMO. 
I am not sure about this library...
@righettod what is your opinion?

**Comment by aussieklutz** [comment] 2019-05-24 02:22
This suggestion, to remove complexity, and suggest length also aligns better with the latest NIST memorized secrets recommendations.

**Comment by mackowski** [comment] 2019-05-30 07:59
With @ThunderSon we agreed that we should mention the library, and put a note of the non-maintainability of the library.

@fabienleite Can I assign this issue to you?

**Comment by fabienleite** [comment] 2019-05-30 12:29
Yes, please go on. I will work on it as soon as I can.

**Comment by mackowski** [comment] 2019-05-30 13:39
Sure, there is no rush at all. Thank you for your engagement!

**Comment by mackowski** [comment] 2019-07-26 07:01
I will take it since this is open for a long time now.

**Comment by fabienleite** [comment] 2019-07-26 14:43
I'm **so sorry**. I'll try to do this this weekend, if I don't give you feedback before Monday, please do it.  

I didn't have much time as I was busy with a lot of things recently but I begin to have a little bit more time to think about it.

**Comment by righettod** [comment] 2019-08-05 07:49
PR #167 merged.

**Closed by righettod** 2019-08-05 07:49 UTC
Labels: ACK_OBTAINED, UPDATE_CS
