### ISSUE TITLE
TLS CS update proposal: Rule - Do Not Use Wildcard Certificates

### ISSUE THREAD

**Issue by buztheflash** [OWASP/CheatSheetSeries#158] opened 2019-07-17 12:42 UTC
Hello,

Thank you very much for this cheat cheet.
I would like to propose to update the "Rule - Do Not Use Wildcard Certificates" detailling this part: "obtaining access to the private key is left as an exercise for the attacker, but its made much easier when stored on the file system unprotected".
1) Why is this private key retrieval easier specifically for wildcard certificates? And provide more details about the attack path.
2) We could define some exceptions to the use of wildcard. I see one use-case where wildcard certificates may be useful and secure. If we have a solution (called solutionA) that is a used by many customers, and we regularly onboard new customers: “customer1.solutionA.prod.companydomain.io”, “customer2.solutionA. prod.companydomain.io”,.. then a wildcard certificate for “*.solutionA. prod.companydomain.io” could be useful and dedicated to the solution only. This certificate could be embedded in mobile apps (certificate pinning) or iot devices whatever the customer is. 
Your feedback is very welcome.
Thank you for your support.
Kind regards,
Philippe

**Comment by mackowski** [comment] 2019-07-18 06:15
Hey, this can be a good addition to this CS. What do you think @ThunderSon and @righettod.

**Comment by ThunderSon** [comment] 2019-07-18 07:11
Let this issue handle a refactoring of that whole section. Especially the point about EVs as it is bad and obsolete. @buztheflash Are you able to create a PR for this issue?
Pretty sure there are use cases for the wildcard certificates, pros and cons. The section above it will need a couple of amendments as well as they tackle the same topic.

**Comment by buztheflash** [comment] 2019-07-18 11:22
I will create a PR for this request. Thank you!

**Comment by mackowski** [comment] 2019-07-18 11:23
Awesome! Thank you @buztheflash

**Comment by mackowski** [comment] 2019-07-31 07:10
@buztheflash I see that you done it but you did not created PR to this project. Do you need any help?

**Comment by buztheflash** [comment] 2019-08-01 12:44
Hi @mackowski,
Oops! I would appreciate some support about how to implement the process! As you know this is my first collaboration! Thank you in advance

**Comment by bschach** [comment] 2019-08-07 21:52
Sorry to jump in here, but I recently looked for a good overview of the wildcard certificate topic and came across a good article by Sean Wright (https://blog.sean-wright.com/wildcard-certs-not-quite-the-star/)

Also, in case this helps, here's some of my conclusions regarding the topic:

Pros:
- often considered cheaper and easier to manage than specific certificates (unless compared to Let's Encrypt)
- provides flexibility with dynamically generated new subdomains (e.g. 
  - tenant1.saas-service.companydomain.io, 
  - tenant2.saas-service.companydomain.io)

Cons:
- Compromise of one server and leakage of the private key affects
  - all systems using the wildcard certificate, by allowing an attacker to perform e.g. MITM attacks
  - all systems running directly under the affected wildcard domain (no matter whether they use the wildcard certificate or individual specific certificates), by allowing an attacker to pose as one of the servers, e.g. if additional DNS spoofing is possible
- If used widely, timely revocation of a certificate in case of a breach will be nearly impossible (or alternatively render all sites "insecure")

Recommendations:
- Do not use wildcard certificates
- If absolutely needed:
  - Don't use them for top-level domains
  - Only use them for specific sub domains that are
    - completely under your control
    - used only for 1 specific use case/service

Please let me know, if this is helpful or if I got anything wrong. Wording can surely be improved.

(btw, what I also didn't know: the wildcard only covers one level of subdomains (the asterisk doesn't match full stops)

**Comment by ThunderSon** [comment] 2019-08-08 04:42
@buztheflash Hi! What exactly do you need as assistance? Your comment totally slipped under the radar 😄 
@bschach What you wrote is amazing. Not everything is part of this issue, but is something to be considered for the CS.
An interesting read as well was this [gist](https://gist.github.com/joepie91/7e5cad8c0726fd6a5e90360a754fc568)

**Comment by righettod** [comment] 2019-08-23 17:19
Hello, 

As the issue is assigned since many time and we do not have received any PR for this then we send it back to the backlog and we set it as **HELP_WANTED**.

Thank you very much in advance for your understanding 😃

**Comment by rbsec** [comment] 2019-09-01 09:06
Hi,

As part of a rewrite of the Transport Layer Protection CS (#202) I've updated the wildcard certificate guidance based on the discussion here and elsewhere.

Any feedback you have on the proposed new content is welcome:

https://github.com/rbsec/CheatSheetSeries/blob/tls/cheatsheets/Transport_Layer_Protection_Cheat_Sheet.md#carefully-consider-the-use-of-wildcard-certificates

Thanks

**Comment by righettod** [comment] 2019-09-01 09:42
Perhaps we can say that this issue is handled in #202  ?

**Comment by rbsec** [comment] 2019-09-01 10:33
It should be resolved when #202 is merged, I was mostly commenting here to get some feedback from the earlier discussion.

**Comment by righettod** [comment] 2019-09-14 06:28
PR #202 merge and it has handled this point.

**Closed by righettod** 2019-09-14 06:28 UTC
Labels: ACK_OBTAINED, UPDATE_CS
